accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('login/url/', views.RequestLoginViaUrlView.as_view(), name='request_login_via_url'),
    path('login/<uidb64>/<token>/', views.login_via_url, name='login_via_url'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.MyPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', views.MyPasswordConfirmView.as_view(), name='password_reset_confirm'),
]

blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
  path('', views.post_list, name='post_list'),
  path('<int:pk>/', views.post_detail, name='post_detail'),
]

server/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('blog:post_list'), name='root'),
]

accounts/models.py
from django.core.mail import send_mail
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    website_url = models.URLField(blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)

    # send_mail(
    #     '환영합니다',
    #     'Here is the message.',
    #     'me@ldy.com',
    #     [user.email],
    #     fail_silently=False,
    # )


post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

blog/models.py
from django.db import models


class Post(models.Model):
  title = models.CharField(max_length=100)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email


class SignupForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].validators = [validate_email]
        self.fields['username'].help_text = 'Enter Email Format.'
        self.fields['username'].label = 'Email'

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = user.username
        if commit:
            user.save()
        return user

    '''
    def clean_username(self):
        value = self.cleaned_data.get('username')
        if value:
            validate_email(value)
        return value
    '''

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetView, PasswordChangeView, PasswordResetConfirmView
from django.http import Http404
from django.utils.http import urlsafe_base64_decode
from django.shortcuts import render, redirect, resolve_url
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import SignupForm

'''
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            next_url = request.GET.get('next') or 'profile'
            return redirect(next_url)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })
'''


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'

    def get_success_url(self):
        next_url = self.request.GET.get('next') or 'profile'
        return resolve_url(next_url)

    def form_valid(self, form):
        user = form.save()
        auth_login(self.request, user)
        return redirect(self.get_success_url())


signup = SignupView.as_view()
# signup = CreateView.as_view(model=User,
#                             form_class=UserCreationForm,
#                             success_url=settings.LOGIN_URL,
#                             template_name='accounts/signup.html')


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


class RequestLoginViaUrlView(PasswordResetView):
    template_name = 'accounts/request_login_via_url_form.html'
    title = '이메일을 통한 로그인'
    email_template_name = 'accounts/login_via_url.html'
    success_url = settings.LOGIN_URL


def login_via_url(request, uidb64, token):

    User = get_user_model()

    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        raise Http404

    if default_token_generator.check_token(current_user, token):
        auth_login(request, current_user)
        messages.info(request, '로그인이 승인되었습니다.')
        return redirect('root')

    messages.error(request, '로그인이 거부되었습니다.')
    return redirect('root')


class MyPasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('profile')
    template_name = 'accounts/password_change_form.html'

    def form_valid(self, form):
        messages.info(self.request, '암호 변경을 완료했습니다.')
        return super().form_valid(form)


class MyPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('login')
    template_name = "accounts/password_reset_form.html"

    def form_valid(self, form):
        messages.info(self.request, '암호 변경 메일을 발송했습니다.')
        return super().form_valid(form)


class MyPasswordConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('login')
    template_name = "accounts/password_reset_confirm.html"

    def form_valid(self, form):
        messages.info(self.request, '암호 리셋을 완료했습니다.')
        return super().form_valid(form)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post


post_list = ListView.as_view(model=Post)

post_detail = DetailView.as_view(model=Post)

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/login.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

accounts/templates/accounts/login_via_url.html
아래 주소를 통해 {{ site_name }}에 로그인하실 수 있습니다.

링크: {{ protocol }}://{{ domain }}{% url "login_via_url" uidb64=uid token=token %}

accounts/templates/accounts/password_change_done.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>암호 변경 완료</h2>

    암호 변경을 완료했습니다.
{% endblock %}

accounts/templates/accounts/password_change_form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>암호 변경</h2>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit">
    </form>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>새 비밀번호 입력</h2>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>암호 리셋 요청하기</h2>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>

    <hr />

    <a href='{% url "login" %}'>로그인</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}

    <h2>{{ user.username }}'s Profile</h2>
    <h3>Email</h3>
    {{  user.email }}
    <h3> Bio </h3>
    {{ user.profile.bio|default:"empty" }}

    <hr/>

    <a href='{% url "password_change" %}'>암호 변경하기</a>
{% endblock %}

accounts/templates/accounts/request_login_via_url_form.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>이메일로 로그인</h2>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit">
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}

    <h2>{{ post.title }}</h2>

    {{ post.content | linebreaks }}

    <hr />

    <a href='{% url "blog:post_list" %}'>글 목록</a>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}

    <table>
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>
                        <a href='{% url "blog:post_detail" post.pk %}'>
                            {{ post.title }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

server/templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>AskDjango Blog</title>
</head>
<body>
  <h1>
    <a href='{% url "root" %}'>AskDjango Blog</a>
  </h1>

  {% if user.is_authenticated %}
    <a href='{% url "profile" %}'>{{ user }}</a>
    <a href='{% url "logout" %}?next={{ request.path }}' onclick='return confirm("are you sure?")'>로그아웃</a>
  {% else %}
    <a href='{% url "signup" %}?next={{ request.path }}'>회원가입</a>
    <a href='{% url "login" %}?next={{ request.path }}'>로그인</a>
  {% endif %}

  <hr/>

  {% block content %}
  {% endblock %}

  <hr/>
  %copy; .......
</body>
</html>